// Code generated by mockigo. DO NOT EDIT.

package foo

import foo "github.com/subtle-byte/mockigo/internal/fixtures/mockery/example_project/foo"
import match "github.com/subtle-byte/mockigo/match"
import mock "github.com/subtle-byte/mockigo/mock"

var _ = match.Any[int]

type Foo struct {
	mock *mock.Mock
}

func NewFoo(t mock.Testing) *Foo {
	t.Helper()
	return &Foo{mock: mock.NewMock(t)}
}

type _Foo_Expecter struct {
	mock *mock.Mock
}

func (_mock *Foo) EXPECT() _Foo_Expecter {
	 return _Foo_Expecter{mock: _mock.mock}
}

type _Foo_DoFoo_Call struct {
	*mock.Call
}

func (_mock *Foo) DoFoo() (string) {
	_mock.mock.T.Helper()
	_results := _mock.mock.Called("DoFoo", )
	_r0 := _results.Get(0).(string)
	return _r0
}

func (_expecter _Foo_Expecter) DoFoo() _Foo_DoFoo_Call {
	return _Foo_DoFoo_Call{Call: _expecter.mock.ExpectCall("DoFoo", )}
}

func (_call _Foo_DoFoo_Call) Return(_r0 string) _Foo_DoFoo_Call {
	_call.Call.Return(_r0)
	return _call
}

func (_call _Foo_DoFoo_Call) RunReturn(f func() (string)) _Foo_DoFoo_Call {
	_call.Call.RunReturn(f)
	return _call
}

type _Foo_GetBaz_Call struct {
	*mock.Call
}

func (_mock *Foo) GetBaz() (*foo.Baz, error) {
	_mock.mock.T.Helper()
	_results := _mock.mock.Called("GetBaz", )
	var _r0 *foo.Baz
	if _got := _results.Get(0); _got != nil {
		_r0 = _got.(*foo.Baz)
	}
	_r1 := _results.Error(1)
	return _r0, _r1
}

func (_expecter _Foo_Expecter) GetBaz() _Foo_GetBaz_Call {
	return _Foo_GetBaz_Call{Call: _expecter.mock.ExpectCall("GetBaz", )}
}

func (_call _Foo_GetBaz_Call) Return(_r0 *foo.Baz, _r1 error) _Foo_GetBaz_Call {
	_call.Call.Return(_r0, _r1)
	return _call
}

func (_call _Foo_GetBaz_Call) RunReturn(f func() (*foo.Baz, error)) _Foo_GetBaz_Call {
	_call.Call.RunReturn(f)
	return _call
}
