// Code generated by mockigo. DO NOT EDIT.

package some_interface

import match "github.com/subtle-byte/mockigo/match"
import mock "github.com/subtle-byte/mockigo/mock"

var _ = match.Any[int]

type SomeInterface struct {
	mock *mock.Mock
}

func NewSomeInterface(t mock.Testing) *SomeInterface {
	t.Helper()
	return &SomeInterface{mock: mock.NewMock(t)}
}

type _SomeInterface_Expecter struct {
	mock *mock.Mock
}

func (_mock *SomeInterface) EXPECT() _SomeInterface_Expecter {
	 return _SomeInterface_Expecter{mock: _mock.mock}
}

type _SomeInterface_SomeMethod_Call struct {
	*mock.Call
}

func (_mock *SomeInterface) SomeMethod() (int) {
	_mock.mock.T.Helper()
	_results := _mock.mock.Called("SomeMethod", )
	_r0 := _results.Get(0).(int)
	return _r0
}

func (_expecter _SomeInterface_Expecter) SomeMethod() _SomeInterface_SomeMethod_Call {
	return _SomeInterface_SomeMethod_Call{Call: _expecter.mock.ExpectCall("SomeMethod", )}
}

func (_call _SomeInterface_SomeMethod_Call) Return(_r0 int) _SomeInterface_SomeMethod_Call {
	_call.Call.Return(_r0)
	return _call
}

func (_call _SomeInterface_SomeMethod_Call) RunReturn(f func() (int)) _SomeInterface_SomeMethod_Call {
	_call.Call.RunReturn(f)
	return _call
}
