// Code generated by mockigo. DO NOT EDIT.

//go:generate mockigo 

package foo

import match "github.com/subtle-byte/mockigo/match"
import mock "github.com/subtle-byte/mockigo/mock"

var _ = match.Any[int]

type ClientMock struct {
	mock *mock.Mock
}

func NewClientMock(t mock.Testing) *ClientMock {
	t.Helper()
	return &ClientMock{mock: mock.NewMock(t)}
}

type _ClientMock_Expecter struct {
	mock *mock.Mock
}

func (_mock *ClientMock) EXPECT() _ClientMock_Expecter {
	 return _ClientMock_Expecter{mock: _mock.mock}
}

type _ClientMock_Search_Call struct {
	*mock.Call
}

func (_mock *ClientMock) Search(query string) ([]string, error) {
	_mock.mock.T.Helper()
	_results := _mock.mock.Called("Search", query)
	var _r0 []string
	if _got := _results.Get(0); _got != nil {
		_r0 = _got.([]string)
	}
	_r1 := _results.Error(1)
	return _r0, _r1
}

func (_expecter _ClientMock_Expecter) Search(query match.Arg[string]) _ClientMock_Search_Call {
	return _ClientMock_Search_Call{Call: _expecter.mock.ExpectCall("Search", query.Matcher)}
}

func (_call _ClientMock_Search_Call) Return(_r0 []string, _r1 error) _ClientMock_Search_Call {
	_call.Call.Return(_r0, _r1)
	return _call
}

func (_call _ClientMock_Search_Call) RunReturn(f func(query string) ([]string, error)) _ClientMock_Search_Call {
	_call.Call.RunReturn(f)
	return _call
}
