// Code generated by mockigo. DO NOT EDIT.

package data

import match "github.com/subtle-byte/mockigo/match"
import mock "github.com/subtle-byte/mockigo/mock"

var _ = match.Any[int]

type Func struct {
	mock *mock.Mock
}

func NewFunc(t mock.Testing) *Func {
	t.Helper()
	return &Func{mock: mock.NewMock(t)}
}

type _Func_Expecter struct {
	mock *mock.Mock
}

func (_mock *Func) EXPECT() _Func_Expecter {
	 return _Func_Expecter{mock: _mock.mock}
}

type _Func_Execute_Call struct {
	*mock.Call
}

func (_mock *Func) Execute() () {
	_mock.mock.T.Helper()
	_mock.mock.Called("Execute", )
}

func (_expecter _Func_Expecter) Execute() _Func_Execute_Call {
	return _Func_Execute_Call{Call: _expecter.mock.ExpectCall("Execute", )}
}

func (_call _Func_Execute_Call) Return() _Func_Execute_Call {
	_call.Call.Return()
	return _call
}

func (_call _Func_Execute_Call) RunReturn(f func() ()) _Func_Execute_Call {
	_call.Call.RunReturn(f)
	return _call
}
