// Code generated by mockigo. DO NOT EDIT.

package data

import match "github.com/subtle-byte/mockigo/match"
import mock "github.com/subtle-byte/mockigo/mock"

var _ = match.Any[int]

type Nilable struct {
	mock *mock.Mock
}

func NewNilable(t mock.Testing) *Nilable {
	t.Helper()
	return &Nilable{mock: mock.NewMock(t)}
}

type _Nilable_Expecter struct {
	mock *mock.Mock
}

func (_mock *Nilable) EXPECT() _Nilable_Expecter {
	 return _Nilable_Expecter{mock: _mock.mock}
}
