// Code generated by mockigo. DO NOT EDIT.

package data

import match "github.com/subtle-byte/mockigo/match"
import mock "github.com/subtle-byte/mockigo/mock"

var _ = match.Any[int]

type NotExported struct {
	mock *mock.Mock
}

func NewNotExported(t mock.Testing) *NotExported {
	t.Helper()
	return &NotExported{mock: mock.NewMock(t)}
}

type _NotExported_Expecter struct {
	mock *mock.Mock
}

func (_mock *NotExported) EXPECT() _NotExported_Expecter {
	 return _NotExported_Expecter{mock: _mock.mock}
}
