// Code generated by mockigo. DO NOT EDIT.

//go:generate mockigo 

package context

import context "context"
import match "github.com/subtle-byte/mockigo/match"
import mock "github.com/subtle-byte/mockigo/mock"

var _ = match.Any[int]

type CollideWithStdLibMock struct {
	mock *mock.Mock
}

func NewCollideWithStdLibMock(t mock.Testing) *CollideWithStdLibMock {
	t.Helper()
	return &CollideWithStdLibMock{mock: mock.NewMock(t)}
}

type _CollideWithStdLibMock_Expecter struct {
	mock *mock.Mock
}

func (_mock *CollideWithStdLibMock) EXPECT() _CollideWithStdLibMock_Expecter {
	 return _CollideWithStdLibMock_Expecter{mock: _mock.mock}
}

type _CollideWithStdLibMock_NewClient_Call struct {
	*mock.Call
}

func (_mock *CollideWithStdLibMock) NewClient(ctx context.Context) () {
	_mock.mock.T.Helper()
	_mock.mock.Called("NewClient", ctx)
}

func (_expecter _CollideWithStdLibMock_Expecter) NewClient(ctx match.Arg[context.Context]) _CollideWithStdLibMock_NewClient_Call {
	return _CollideWithStdLibMock_NewClient_Call{Call: _expecter.mock.ExpectCall("NewClient", ctx.Matcher)}
}

func (_call _CollideWithStdLibMock_NewClient_Call) Return() _CollideWithStdLibMock_NewClient_Call {
	_call.Call.Return()
	return _call
}

func (_call _CollideWithStdLibMock_NewClient_Call) RunReturn(f func(ctx context.Context) ()) _CollideWithStdLibMock_NewClient_Call {
	_call.Call.RunReturn(f)
	return _call
}
