// Code generated by mockigo. DO NOT EDIT.

package test

import match "github.com/subtle-byte/mockigo/match"
import mock "github.com/subtle-byte/mockigo/mock"

var _ = match.Any[int]

type Blank struct {
	mock *mock.Mock
}

func NewBlank(t mock.Testing) *Blank {
	t.Helper()
	return &Blank{mock: mock.NewMock(t)}
}

type _Blank_Expecter struct {
	mock *mock.Mock
}

func (_mock *Blank) EXPECT() _Blank_Expecter {
	 return _Blank_Expecter{mock: _mock.mock}
}

type _Blank_Create_Call struct {
	*mock.Call
}

func (_mock *Blank) Create(x interface{}) (error) {
	_mock.mock.T.Helper()
	_results := _mock.mock.Called("Create", x)
	_r0 := _results.Error(0)
	return _r0
}

func (_expecter _Blank_Expecter) Create(x match.Arg[interface{}]) _Blank_Create_Call {
	return _Blank_Create_Call{Call: _expecter.mock.ExpectCall("Create", x.Arg)}
}

func (_call _Blank_Create_Call) Return(_r0 error) _Blank_Create_Call {
	_call.Call.Return(_r0)
	return _call
}

func (_call _Blank_Create_Call) RunReturn(f func(x interface{}) (error)) _Blank_Create_Call {
	_call.Call.RunReturn(f)
	return _call
}
