// Code generated by mockigo. DO NOT EDIT.

package mockery

import match "github.com/subtle-byte/mockigo/match"
import mock "github.com/subtle-byte/mockigo/mock"

var _ = match.Any[int]

type Requester4 struct {
	mock *mock.Mock
}

func NewRequester4(t mock.Testing) *Requester4 {
	t.Helper()
	return &Requester4{mock: mock.NewMock(t)}
}

type _Requester4_Expecter struct {
	mock *mock.Mock
}

func (_mock *Requester4) EXPECT() _Requester4_Expecter {
	 return _Requester4_Expecter{mock: _mock.mock}
}

type _Requester4_Get_Call struct {
	*mock.Call
}

func (_mock *Requester4) Get() () {
	_mock.mock.T.Helper()
	_mock.mock.Called("Get", )
}

func (_expecter _Requester4_Expecter) Get() _Requester4_Get_Call {
	return _Requester4_Get_Call{Call: _expecter.mock.ExpectCall("Get", )}
}

func (_call _Requester4_Get_Call) Return() _Requester4_Get_Call {
	_call.Call.Return()
	return _call
}

func (_call _Requester4_Get_Call) RunReturn(f func() ()) _Requester4_Get_Call {
	_call.Call.RunReturn(f)
	return _call
}
