// Code generated by mockigo. DO NOT EDIT.

package test

import io "io"
import match "github.com/subtle-byte/mockigo/match"
import mock "github.com/subtle-byte/mockigo/mock"

var _ = match.Any[int]

type RequesterIface struct {
	mock *mock.Mock
}

func NewRequesterIface(t mock.Testing) *RequesterIface {
	t.Helper()
	return &RequesterIface{mock: mock.NewMock(t)}
}

type _RequesterIface_Expecter struct {
	mock *mock.Mock
}

func (_mock *RequesterIface) EXPECT() _RequesterIface_Expecter {
	 return _RequesterIface_Expecter{mock: _mock.mock}
}

type _RequesterIface_Get_Call struct {
	*mock.Call
}

func (_mock *RequesterIface) Get() (io.Reader) {
	_mock.mock.T.Helper()
	_results := _mock.mock.Called("Get", )
	var _r0 io.Reader
	if _got := _results.Get(0); _got != nil {
		_r0 = _got.(io.Reader)
	}
	return _r0
}

func (_expecter _RequesterIface_Expecter) Get() _RequesterIface_Get_Call {
	return _RequesterIface_Get_Call{Call: _expecter.mock.ExpectCall("Get", )}
}

func (_call _RequesterIface_Get_Call) Return(_r0 io.Reader) _RequesterIface_Get_Call {
	_call.Call.Return(_r0)
	return _call
}

func (_call _RequesterIface_Get_Call) RunReturn(f func() (io.Reader)) _RequesterIface_Get_Call {
	_call.Call.RunReturn(f)
	return _call
}
