// Code generated by mockigo. DO NOT EDIT.

package test

import match "github.com/subtle-byte/mockigo/match"
import mock "github.com/subtle-byte/mockigo/mock"

var _ = match.Any[int]

type RequesterSlice struct {
	mock *mock.Mock
}

func NewRequesterSlice(t mock.Testing) *RequesterSlice {
	t.Helper()
	return &RequesterSlice{mock: mock.NewMock(t)}
}

type _RequesterSlice_Expecter struct {
	mock *mock.Mock
}

func (_mock *RequesterSlice) EXPECT() _RequesterSlice_Expecter {
	 return _RequesterSlice_Expecter{mock: _mock.mock}
}

type _RequesterSlice_Get_Call struct {
	*mock.Call
}

func (_mock *RequesterSlice) Get(path string) ([]string, error) {
	_mock.mock.T.Helper()
	_results := _mock.mock.Called("Get", path)
	var _r0 []string
	if _got := _results.Get(0); _got != nil {
		_r0 = _got.([]string)
	}
	_r1 := _results.Error(1)
	return _r0, _r1
}

func (_expecter _RequesterSlice_Expecter) Get(path match.Arg[string]) _RequesterSlice_Get_Call {
	return _RequesterSlice_Get_Call{Call: _expecter.mock.ExpectCall("Get", path.Arg)}
}

func (_call _RequesterSlice_Get_Call) Return(_r0 []string, _r1 error) _RequesterSlice_Get_Call {
	_call.Call.Return(_r0, _r1)
	return _call
}

func (_call _RequesterSlice_Get_Call) RunReturn(f func(path string) ([]string, error)) _RequesterSlice_Get_Call {
	_call.Call.RunReturn(f)
	return _call
}
