// Code generated by mockigo. DO NOT EDIT.

package mockery

import http "net/http"
import match "github.com/subtle-byte/mockigo/match"
import mock "github.com/subtle-byte/mockigo/mock"

var _ = match.Any[int]

type RequesterNS struct {
	mock *mock.Mock
}

func NewRequesterNS(t mock.Testing) *RequesterNS {
	t.Helper()
	return &RequesterNS{mock: mock.NewMock(t)}
}

type _RequesterNS_Expecter struct {
	mock *mock.Mock
}

func (_mock *RequesterNS) EXPECT() _RequesterNS_Expecter {
	 return _RequesterNS_Expecter{mock: _mock.mock}
}

type _RequesterNS_Get_Call struct {
	*mock.Call
}

func (_mock *RequesterNS) Get(path string) (http.Response, error) {
	_mock.mock.T.Helper()
	_results := _mock.mock.Called("Get", path)
	_r0 := _results.Get(0).(http.Response)
	_r1 := _results.Error(1)
	return _r0, _r1
}

func (_expecter _RequesterNS_Expecter) Get(path match.Arg[string]) _RequesterNS_Get_Call {
	return _RequesterNS_Get_Call{Call: _expecter.mock.ExpectCall("Get", path.Arg)}
}

func (_call _RequesterNS_Get_Call) Return(_r0 http.Response, _r1 error) _RequesterNS_Get_Call {
	_call.Call.Return(_r0, _r1)
	return _call
}

func (_call _RequesterNS_Get_Call) RunReturn(f func(path string) (http.Response, error)) _RequesterNS_Get_Call {
	_call.Call.RunReturn(f)
	return _call
}
