// Code generated by mockigo. DO NOT EDIT.

package mockery

import match "github.com/subtle-byte/mockigo/match"
import mock "github.com/subtle-byte/mockigo/mock"

var _ = match.Any[int]

type Requester2 struct {
	mock *mock.Mock
}

func NewRequester2(t mock.Testing) *Requester2 {
	t.Helper()
	return &Requester2{mock: mock.NewMock(t)}
}

type _Requester2_Expecter struct {
	mock *mock.Mock
}

func (_mock *Requester2) EXPECT() _Requester2_Expecter {
	 return _Requester2_Expecter{mock: _mock.mock}
}

type _Requester2_Get_Call struct {
	*mock.Call
}

func (_mock *Requester2) Get(path string) (error) {
	_mock.mock.T.Helper()
	_results := _mock.mock.Called("Get", path)
	_r0 := _results.Error(0)
	return _r0
}

func (_expecter _Requester2_Expecter) Get(path match.Arg[string]) _Requester2_Get_Call {
	return _Requester2_Get_Call{Call: _expecter.mock.ExpectCall("Get", path.Arg)}
}

func (_call _Requester2_Get_Call) Return(_r0 error) _Requester2_Get_Call {
	_call.Call.Return(_r0)
	return _call
}

func (_call _Requester2_Get_Call) RunReturn(f func(path string) (error)) _Requester2_Get_Call {
	_call.Call.RunReturn(f)
	return _call
}
