// Code generated by mockigo. DO NOT EDIT.

package mockery

import match "github.com/subtle-byte/mockigo/match"
import mock "github.com/subtle-byte/mockigo/mock"

var _ = match.Any[int]

type RequesterArray struct {
	mock *mock.Mock
}

func NewRequesterArray(t mock.Testing) *RequesterArray {
	t.Helper()
	return &RequesterArray{mock: mock.NewMock(t)}
}

type _RequesterArray_Expecter struct {
	mock *mock.Mock
}

func (_mock *RequesterArray) EXPECT() _RequesterArray_Expecter {
	 return _RequesterArray_Expecter{mock: _mock.mock}
}

type _RequesterArray_Get_Call struct {
	*mock.Call
}

func (_mock *RequesterArray) Get(path string) ([2]string, error) {
	_mock.mock.T.Helper()
	_results := _mock.mock.Called("Get", path)
	var _r0 [2]string
	if _got := _results.Get(0); _got != nil {
		_r0 = _got.([2]string)
	}
	_r1 := _results.Error(1)
	return _r0, _r1
}

func (_expecter _RequesterArray_Expecter) Get(path match.Arg[string]) _RequesterArray_Get_Call {
	return _RequesterArray_Get_Call{Call: _expecter.mock.ExpectCall("Get", path.Arg)}
}

func (_call _RequesterArray_Get_Call) Return(_r0 [2]string, _r1 error) _RequesterArray_Get_Call {
	_call.Call.Return(_r0, _r1)
	return _call
}

func (_call _RequesterArray_Get_Call) RunReturn(f func(path string) ([2]string, error)) _RequesterArray_Get_Call {
	_call.Call.RunReturn(f)
	return _call
}
